#!/bin/sh
while true;
do
	echo "DTrace run; output file: "`pwd`"/.microprofilepipe"
	mkfifo .microprofilepipe
	dtrace -q -n fbt::thread_dispatch:return'{printf("MPTD %x %x %x\n", cpu, tid, machtimestamp)}' -o .microprofilepipe
	rm .microprofilepipe
	read -p "DTrace run finished, press Enter to restart..."
done
